sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35

before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get update -qq
  - sudo apt-get install golang

install:
  - pip install tox codecov
  - go build -o src/cryptography_gocrypto/gocrypto.so -buildmode=c-shared gosrc/main.go

script:
  - tox

after_success:
  - |
    codecov

notifications:
  email: false
