sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/go
env:
  global:
    - GO_VERSION=1.6.2
    - PATH=$HOME/go/bin:$PATH
    - GOPATH=$HOME/go

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35

before_install:
  - mkdir -p $HOME/go
  - curl -z $HOME/go/go1.6.2.linux-amd64.tar.gz -o $HOME/go/go1.6.2.linux-amd64.tar.gz https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz
  - tar -C $HOME -xzf $HOME/go/go$GO_VERSION.linux-amd64.tar.gz
  - go get golang.org/x/crypto/...

install:
  - pip install tox codecov
  - go build -o src/cryptography_gocrypto/gocrypto.so -buildmode=c-shared gosrc/main.go

script:
  - tox

after_success:
  - |
    codecov

notifications:
  email: false
